[logger]
    mode = "debug"
    timestamp = "time"

[authorization]
    [[authorization.users]]
        username = "username"
        password = "password"

[api]
    enable = true
    auth = false
    env = "development"

[data]
    templates = "templates"
    store = "store"
    states = [
        "default/state1.json",
        "default/state2.json"
    ]